eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauleZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
app.provider.url=http://localhost:9090/placeorder/Book
